### ISSUE TITLE
Is it possible to prevent the automatic translation

### ISSUE THREAD

**Issue by JanMisker** [Featurable/react-google-reviews#4]
The reviews are shown with automatic translation, which doesn't make sense for us because we want to show reviews in Dutch on a Dutch website.
Is it possible to disable the translation?

**Comment by ryanschiang** [comment]
Thanks for the feedback! 

I've added a [`disableTranslation`](https://github.com/Featurable/react-google-reviews?tab=readme-ov-file#common-props) prop to the `<ReactGoogleReviews>` component that will always use the original text (if it exists) and hide Google's translations. 

Let me know if this works for your case. Thanks!

**Comment by JanMisker** [comment]
I appreciate you following up relatively quickly, but I already 'rolled my own' based on Google Places API. 
I'll keep this package in mind for a next project.

**Comment by ryanschiang** [comment]
Got it, no worries! If you're ever looking for more than 5 reviews from the Google Places API, hope you'll give this package a try again.
