### ISSUE TITLE
Feature request : add a way to translate labels 

### ISSUE THREAD

**Issue by ericjeansmith** [Featurable/react-google-reviews#5]
Hi,
First of all, thanks for this tool!

As I am using your widgets for a non-english web site, would it be possible to add a way to translate labels like "Read more" "Read less" and relative time display like "1month ago"
An easy way would be to provide the labels and for the date to provide a custom "getRelativeDate()" method ?

Thanks !
Eric

**Comment by ryanschiang** [comment]
Hey Eric,

Thanks for the suggestion! I've added some basic props for overriding the labels and date formatting.

You can now use these props on the `ReactGoogleReviews` component on the latest release `react-google-reviews@1.6.1`

- `badgeLabel?: string`
- `badgeSubheadingFormatter?: (totalReviewCount: number) => string`
- `readMoreLabel?: string`
- `readLessLabel?: string`
- `getRelativeDate?: (date: Date) => string`
- `getAbsoluteDate?: (date: Date) => string`
- `loadingMessage?: React.ReactNode`
- `errorMessage?: React.ReactNode`

The README has documentation on these props now too. If there's any props that I missed, please feel free to let me know. Thanks for the suggestion!

**Comment by ericjeansmith** [comment]
Hey Ryan,

Thanks a lot for providing a version as fast as that !
`readLessLabel` and `readMoreLabel `works well but, I cannot manage to have either `getRelativeDate` or `getAbsoluteDate ` working.
Here is my test code : 
```
<ReactGoogleReviews layout="carousel"
                                    reviews={reviews}
                                    getRelativeDate={(date)=>{return "TEST"}}
                                    readMoreLabel={"Voir plus"}
                                    readLessLabel={"Voir moins"} />
```

Thanks !

**Comment by ryanschiang** [comment]
Ah thanks for pointing this out. I've fixed the issue and `getRelativeDate` and `getAbsoluteDate` should be working correclty now on `react-google-reviews@1.6.2`. Thanks!

**Comment by ericjeansmith** [comment]
Hi Ryan,
I works now.
Thanks a lot!
